let correspond = {
    nametag: "nametag",
    enchancelevel: ["enchancelevelfrom", "enchancelevelto"],
    maxunluck: ["maxluckfrom", "maxluckto"],
    basechance: ["basechancefrom", "basechanceto"],
};

items= [
    {
        nametag:"Доспех босса",
        enchancelevel:0,
        maxunluck:0,
        basechance:100,
    },
    {
        nametag:"Доспех босса",
        enchancelevel:1,
        maxunluck:0,
        basechance:100,
    },
    {
        nametag:"Доспех босса",
        enchancelevel:2,
        maxunluck:0,
        basechance:100,
    },
    {
        nametag:"Доспех босса",
        enchancelevel:3,
        maxunluck:0,
        basechance:100,
    },
    {
        nametag:"Доспех босса",
        enchancelevel:4,
        maxunluck:0,
        basechance:100,
    },
    {
        nametag:"Доспех босса",
        enchancelevel:5,
        maxunluck:0,
        basechance:100,
    },
    {
        nametag:"Доспех босса",
        enchancelevel:6,
        maxunluck:0,
        basechance:100,
    },
    {
        nametag:"Доспех босса",
        enchancelevel:7,
        maxunluck:0,
        basechance:90,
    },
    {
        nametag:"Доспех босса",
        enchancelevel:8,
        maxunluck:5,
        basechance:20.4081,
    },
    {
        nametag:"Доспех босса",
        enchancelevel:9,
        maxunluck:7,
        basechance:14.2857,
    },
    {
        nametag:"Доспех босса",
        enchancelevel:10,
        maxunluck:10,
        basechance:10,
    },
    {
        nametag:"Доспех босса",
        enchancelevel:11,
        maxunluck:30,
        basechance:6.666,
    },
    {
        nametag:"Доспех босса",
        enchancelevel:12,
        maxunluck:30,
        basechance:4,
    },
    {
        nametag:"Доспех босса",
        enchancelevel:13,
        maxunluck:40,
        basechance:2.5,
    },
    {
        nametag:"Доспех босса",
        enchancelevel:14,
        maxunluck:40,
        basechance:2,
    },
    {
        nametag:"Доспех босса",
        enchancelevel:15,
        maxunluck:40,
        basechance:13.0769,
    },
    {
        nametag:"Доспех босса",
        enchancelevel:16,
        maxunluck:70,
        basechance:10.625,
    },
    {
        nametag:"Доспех босса",
        enchancelevel:17,
        maxunluck:120,
        basechance:3.4,
    },
    {
        nametag:"Доспех босса",
        enchancelevel:18,
        maxunluck:250,
        basechance:0.51,
    },
    {
        nametag:"Доспех босса",
        enchancelevel:19,
        maxunluck:500,
        basechance:0.2,
    },
    {
        nametag:"Бижутерия",
        enchancelevel:0,
        maxunluck:14,
        basechance:25,
    },
    {
        nametag:"Бижутерия",
        enchancelevel:1,
        maxunluck:30,
        basechance:10,
    },
    {
        nametag:"Бижутерия",
        enchancelevel:2,
        maxunluck:40,
        basechance:7.5,
    },
    {
        nametag:"Бижутерия",
        enchancelevel:3,
        maxunluck:80,
        basechance:2.5,
    },
    {
        nametag:"Бижутерия",
        enchancelevel:4,
        maxunluck:200,
        basechance:0.5,
    },
    {
        nametag:"Экипировка туваллы",
        enchancelevel:0,
        maxunluck:0,
        basechance:100,
    },
    {
        nametag:"Экипировка туваллы",
        enchancelevel:1,
        maxunluck:0,
        basechance:100,
    },
    {
        nametag:"Экипировка туваллы",
        enchancelevel:2,
        maxunluck:0,
        basechance:100,
    },
    {
        nametag:"Экипировка туваллы",
        enchancelevel:3,
        maxunluck:0,
        basechance:100,
    },
    {
        nametag:"Экипировка туваллы",
        enchancelevel:4,
        maxunluck:0,
        basechance:100,
    },
    {
        nametag:"Экипировка туваллы",
        enchancelevel:5,
        maxunluck:0,
        basechance:100,
    },
    {
        nametag:"Экипировка туваллы",
        enchancelevel:6,
        maxunluck:0,
        basechance:100,
    },
    {
        nametag:"Экипировка туваллы",
        enchancelevel:7,
        maxunluck:0,
        basechance:90,
    },
    {
        nametag:"Экипировка туваллы",
        enchancelevel:8,
        maxunluck:0,
        basechance:100,
    },
    {
        nametag:"Экипировка туваллы",
        enchancelevel:9,
        maxunluck:0,
        basechance:50,
    },
    {
        nametag:"Экипировка туваллы",
        enchancelevel:10,
        maxunluck:5,
        basechance:30,
    },
    {
        nametag:"Экипировка туваллы",
        enchancelevel:11,
        maxunluck:12,
        basechance:20,
    },
    {
        nametag:"Экипировка туваллы",
        enchancelevel:12,
        maxunluck:14,
        basechance:15,
    },
    {
        nametag:"Экипировка туваллы",
        enchancelevel:13,
        maxunluck:15,
        basechance:10,
    },
    {
        nametag:"Экипировка туваллы",
        enchancelevel:14,
        maxunluck:25,
        basechance:8,
    },
    {
        nametag:"Экипировка туваллы",
        enchancelevel:15,
        maxunluck:10,
        basechance:17,
    },
    {
        nametag:"Экипировка туваллы",
        enchancelevel:16,
        maxunluck:10,
        basechance:11,
    },
    {
        nametag:"Экипировка туваллы",
        enchancelevel:17,
        maxunluck:30,
        basechance:8,
    },
    {
        nametag:"Экипировка туваллы",
        enchancelevel:18,
        maxunluck:40,
        basechance:5,
    },
    {
        nametag:"Экипировка туваллы",
        enchancelevel:19,
        maxunluck:60,
        basechance:3,
    },
    {
        nametag:"Бижутерия туваллы",
        enchancelevel:0,
        maxunluck:10,
        basechance:70,
    },
    {
        nametag:"Бижутерия туваллы",
        enchancelevel:1,
        maxunluck:20,
        basechance:50,
    },
    {
        nametag:"Бижутерия туваллы",
        enchancelevel:2,
        maxunluck:30,
        basechance:40,
    },
    {
        nametag:"Бижутерия туваллы",
        enchancelevel:3,
        maxunluck:35,
        basechance:30,
    },
    {
        nametag:"Бижутерия туваллы",
        enchancelevel:4,
        maxunluck:40,
        basechance:20,
    },
]